repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 05c1426671b9237fb5e1444dd63aa5731bec0dfb # v3.13.1-1
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci", "-bn", "-w", "-s"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 996abf60411a8d954288ac9856aae7602b80cbda # v0.22.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: bc7af46104f0f5368b95878decf720f9f00c2559 # v3.4.2
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 82ec55bf6a15fa259e1115b3a89adb99cb8827b2 # v9.17.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@9.17.0

  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: ba566610310affb03b323a94f13f560d3e027c68 # v2.3.0
    hooks:
      - id: tofu_validate
      - id: tofu_fmt
      - id: tofu_tflint
        args:
          - --args=--call-module-type=all
